services:
  voucher-management-api:
    image: ${DOCKER_REGISTRY-}vouchermanagementapi
    build:
      context: .
      dockerfile: VoucherManagement.Api/Dockerfile
    depends_on:
      - voucher-management-db
    environment:
      - ConnectionStrings__AppDbConnection=${ConnectionStrings__AppDbConnection}
      - Auth0__Domain=${Auth0__Domain}
      - Auth0__Audience=${Auth0__Audience}
    volumes:
      - ${BRANDING_PATH}:/app/Branding:ro
      - ${PDF_TEMPLATE_PATH}:/app/PdfTemplates/voucher_template.pdf:ro
    networks:
      - voucher-management-network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voucher-api.rule=Host(`${Traefik_Host}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.voucher-api.priority=10"
      - "traefik.http.routers.voucher-api.entrypoints=websecure"
      - "traefik.http.services.voucher-api.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      # nur nötig, wenn deine API KEIN /api im Routing hat:
      #- "traefik.http.middlewares.voucher-api-strip.stripprefix.prefixes=/api"
      #- "traefik.http.routers.voucher-api.middlewares=voucher-api-strip"

  voucher-management-client:
    image: ${DOCKER_REGISTRY-}vouchermanagementclient
    build:
      context: ./VoucherManagement.Client
      dockerfile: Dockerfile
      args:
        VITE_AUTH0_DOMAIN: ${Auth0__Domain}
        VITE_AUTH0_CLIENT_ID: ${Auth0__ClientId}
        VITE_AUTH0_AUDIENCE: ${Auth0__Audience}
        VITE_AUTH0_SCOPE: ${Auth0__Scope}
    depends_on:
      - voucher-management-api
    networks:
      - voucher-management-network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voucher-client.rule=Host(`${Traefik_Host}`)"
      - "traefik.http.routers.voucher-client.priority=20"
      - "traefik.http.routers.voucher-client.entrypoints=websecure"
      - "traefik.http.services.voucher-client.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

  voucher-management-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    networks:
      - voucher-management-network

networks:
  voucher-management-network:
  proxy:
    external: true
